### ISSUE TITLE
Hi, is your pretrained model the same as in original paper?  both trained on Visual Gnome?

### ISSUE THREAD

**Issue by youngfly11** [violetteshev/bottom-up-features#1]

**Comment by violetteshev** [comment]
I just transferred the pretrained model provided in original [repo](https://github.com/peteanderson80/bottom-up-attention) (structure and weights) to PyTorch.

**Comment by youngfly11** [comment]
ok, thank you very much , i just want to confirm that whether the results produced by your code are the same as the original papers?

**Comment by violetteshev** [comment]
I tested the code on a random subset of MSCOCO images and checked that the extracted features are the same as features extracted by original code, but I didn't check the detection performance on any dataset (although it should be the same).

**Comment by youngfly11** [comment]
thanks

**Comment by jbdel** [comment]
> I just transferred the pretrained model provided in original [repo](https://github.com/peteanderson80/bottom-up-attention) (structure and weights) to PyTorch.

Hello violette,

Could you please tell me how you managed to do that ?

**Comment by violetteshev** [comment]
I manually copied all the weights from one model to another.
