### ISSUE TITLE
Batches with multiple images implementation

### ISSUE THREAD

**Issue by achiyaj** [violetteshev/bottom-up-features#11]
Hi, 

First of all, thanks a lot for your useful repository!
For a project I'm working on, I need your code to support batches with multiple images.
Did you try to implement multiple images extraction at some point? If so, what were your difficulties when trying to do so?

**Comment by violetteshev** [comment]
The faster r-cnn implementation, which I'm using, has this single batch restriction. You can check this [issue](https://github.com/jwyang/faster-rcnn.pytorch/issues/29) for possible solution.

**Comment by achiyaj** [comment]
Got it. Thanks for your help!
