### ISSUE TITLE
Lion and tiger

### ISSUE THREAD

**Issue by hishambutt13** [violetteshev/bottom-up-features#12]
Why this model does not identify loin and tiger?

**Comment by violetteshev** [comment]
This model can only detect these [1600 objects](https://github.com/peteanderson80/bottom-up-attention/blob/master/data/genome/1600-400-20/objects_vocab.txt) which it was trained on.

**Comment by hishambutt13** [comment]
Yeah i know that and lion is in these 1600 objects. Thats why i ask

**Comment by violetteshev** [comment]
Well, that's hard to tell without any information. What images did you try? Does it detect any other objects on these images? Try to reduce CONF_THRESH and see if it helps.

**Comment by hishambutt13** [comment]
Yes it detect other objects correctly. I have tried on multiple images of lions and tigers it detects them as cat, dog and bear

**Comment by violetteshev** [comment]
Then my suggestion is that the data used for training didn't contain lots of lions. So the model is biased towards more common animals. What is your task? If you need to detect only lions/wild animals, it might be better to look for a more narrow-focused model. Or fist fine-tune this model for your own data.

**Comment by hishambutt13** [comment]
Yeah that's can be the reason. i am using this to give a caption on image.
Btw thanks for your help.
