### ISSUE TITLE
How to convert caffe model to pytorch model?

### ISSUE THREAD

**Issue by daqingliu** [violetteshev/bottom-up-features#15]
Thanks for your valuable work!
Could you please tell me how to convert one model (e.g., resnet101_faster_rcnn_final_iter_320000.caffemodel) from caffe to pytorch for your codes? Just any convert code or tutorial is fine!

**Comment by violetteshev** [comment]
Hi, I lost some of my pre-processing files unfortunatelly. But the idea is to save caffe weights in npy files, like [here](https://github.com/nilboy/extract-caffe-params/blob/master/extract.py) for example. And then load them into corresponding weights in Pytroch model.

**Comment by daqingliu** [comment]
Thanks!
