### ISSUE TITLE
error while running sh make.sh

### ISSUE THREAD

**Issue by faaizhashmi** [violetteshev/bottom-up-features#2]
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
building 'model.utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/model
creating build/temp.linux-x86_64-3.6/model/utils
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/faaiz/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/faaiz/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/core/include -I/home/faaiz/anaconda3/envs/py36/include/python3.6m -c model/utils/bbox.c -o build/temp.linux-x86_64-3.6/model/utils/bbox.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -B /home/faaiz/anaconda3/envs/py36/compiler_compat -L/home/faaiz/anaconda3/envs/py36/lib -Wl,-rpath=/home/faaiz/anaconda3/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 build/temp.linux-x86_64-3.6/model/utils/bbox.o -o /home/faaiz/Downloads/bottom-up-features/lib/model/utils/cython_bbox.cpython-36m-x86_64-linux-gnu.so
/home/faaiz/anaconda3/envs/py36/compiler_compat/ld: cannot find -lpthread
/home/faaiz/anaconda3/envs/py36/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
Compiling nms kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
ModuleNotFoundError: No module named 'torch.utils.ffi'
Compiling roi pooling kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
ModuleNotFoundError: No module named 'torch.utils.ffi'
Compiling roi align kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
ModuleNotFoundError: No module named 'torch.utils.ffi'
Compiling roi crop kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
ModuleNotFoundError: No module named 'torch.utils.ffi'

**Comment by violetteshev** [comment]
Hi, are you using PyTorch 0.4.0? torch.utils.ffi was deprecated in the newer versions.

This might also help: `pip3 install cffi`

If the error persists, please refer to [faster-rcnn repo](https://github.com/jwyang/faster-rcnn.pytorch), I used their source code and installation scripts.
