### ISSUE TITLE
.npz file

### ISSUE THREAD

**Issue by hishambutt13** [violetteshev/bottom-up-features#4]
Hi there can you please help me in making a .tsv file or files like [this](https://github.com/husthuaan/AoANet/blob/master/scripts/make_bu_data.py) on single image.
It makes two files .npz and .npy using pre-extracted feature from [Here](https://github.com/peteanderson80/bottom-up-attention)

**Comment by violetteshev** [comment]
You can change `save_features` function in this [file](https://github.com/violetteshev/bottom-up-features/blob/master/utils.py) depending on which format you need to use. It may look something like this:
```
def save_features(output_file, features, boxes):
   np.savez_compressed(output_file+'_att.npz', feat=features)
   np.save(output_file+'_fc.npy', features.mean(0))
   np.save(output_file+'_box.npy', boxes)
```

**Comment by hishambutt13** [comment]
@violetteshev thank you so much for your help.
