### ISSUE TITLE
Display Features 

### ISSUE THREAD

**Issue by hishambutt13** [violetteshev/bottom-up-features#8]
How can we display the features that the model detects?

**Comment by violetteshev** [comment]
You can get the coordinates of detected bounding boxes if you run the program with `--boxes` argument and plot them on original images.

**Comment by hishambutt13** [comment]
When i run the program with --boxes it gives this error

```
Model is loaded.
Number of images: 1.
  0%|                                                     | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "extract_features.py", line 110, in <module>
    save_features(output_file, image_feat, image_bboxes)
  File "/home/hisham/Downloads/bottom-up-features/utils.py", line 43, in save_features
    if boxes == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by violetteshev** [comment]
The was a bug in the file, I updated it now.

**Comment by hishambutt13** [comment]
@violetteshev it work now but how can i plot them on original image with labels?
like [this](https://raw.githubusercontent.com/peteanderson80/bottom-up-attention/master/data/demo/rcnn_example.png)

**Comment by violetteshev** [comment]
This code is designed for feature extraction only. It can also output bounding box coordinates, which you can plot with any drawing library like opencv or matplotlib. If you need to plot the labels also, you can use variable `dets` which stores coordinates and predicted class scores. I'd suggest you look at the [original code](https://github.com/peteanderson80/bottom-up-attention/), it has some demo visualisation [here](https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/demo.py), but you'll have to change the list of classes to the [correct one](https://github.com/peteanderson80/bottom-up-attention/blob/master/data/genome/1600-400-20/objects_vocab.txt).

**Comment by hishambutt13** [comment]
@violetteshev okay i will look in this but can it simply output the features that your model detects on command line?

**Comment by violetteshev** [comment]
Each feature is a vector of 2048 numbers, and there are 10-100 features detected for each image. It makes no sense to print them in a command line, so they are saved in a file.

**Comment by hishambutt13** [comment]
Not in machine language. In human readable form like boy,bike,grass etc...

**Comment by violetteshev** [comment]
This code doesn't have this functionality. You can change it yourself or look at the original repo.

**Comment by hishambutt13** [comment]
Okay thanks
